AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Cognito User Pool, App Client, DynamoDB, and Post-Confirmation Lambda for Study Assistant project.

Resources:
  StudyAssistantUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: StudyAssistantUserPool
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: role
          AttributeDataType: String
          Mutable: true
          Required: false  # Changed to optional to avoid schema update errors
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      LambdaConfig:
        PostConfirmation: arn:aws:lambda:us-east-1:209469701524:function:PostConfirmationLambda

  StudyAssistantUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: StudyAssistantClient
      UserPoolId: !Ref StudyAssistantUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      AccessTokenValidity: 1440
      IdTokenValidity: 1440
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
  LambdaCognitoPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: arn:aws:lambda:us-east-1:209469701524:function:PostConfirmationLambda
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt StudyAssistantUserPool.Arn

Outputs:
  UserPoolId:
    Description: The ID of the Cognito User Pool
    Value: !Ref StudyAssistantUserPool
    Export:
      Name: StudyAssistant-UserPool-Id

  UserPoolClientId:
    Description: The ID of the Cognito User Pool Client
    Value: !Ref StudyAssistantUserPoolClient
    Export:
      Name: StudyAssistant-UserPoolClient-Id
